package spaceappschallenge.moonville.businessmodels;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Contains all buildings per level as of 
 * https://www.facebook.com/photo.php?fbid=10151316698507504
 * 
 * @author Felix
 *
 */
public class BuildingTree implements Serializable {
	
	Building building;
	
	List<BuildingTree> childs = new ArrayList<BuildingTree>();
	
	/**
	 * Creates an empty tree.
	 */
	public BuildingTree() {		
	}
	
	/**
	 * Creates a tree using the parameter as value.
	 */
	private BuildingTree(Building building) {
		this.building = building;
	}
	
	/**
	 * Insert a building into the tree. Only call this method on the root 
	 * node of a tree.
	 * 
	 * @param b The building to insert.
	 * @return True if the building was inserted successfully.
	 */
	public boolean add(Building b) {
		if (b == null)
			return true;
		if (b.getName().equals(building.getName())) {
			// Inserted the same building multiple times.
			assert(false);
			return false;
		}
		// First see if the building belongs in an existing child node.
		for (BuildingTree bt : childs) {
			if (bt.add(b)) {
				return true;
			}
		}
		// The building is in a new direct child node if building in 
		// this node is a requirement.
		ArrayList<Building> required = b.getRequiredBuildings();
		for (Building r : required) {
			if (r.getName().equals(building.getName())) {
				childs.add(new BuildingTree(b));
				return true;
			}
		}
		// Insertion went completely wrong.
		assert(false);
		return false;
	}
	
	/**
	 * Gets the total power produced by all buildings, then does a 
	 * breadth-first traversal over the tree, powering buildings 
	 * near the root first, setting Building.hasPower accordingly.
	 * 
	 * This implementation does not consider resources, or required buildings, 
	 * which means a building may be powered while it does actually work.
	 */
	public void checkPower() {
		int power = computeTotalPowerOutput();
		List<BuildingTree> q = new ArrayList<BuildingTree>();
		q.add(this);
		while (!q.isEmpty()) {
			BuildingTree v = q.get(0);
			q.remove(v);
			if (v.building == null)
				continue;
			if (v.building.getInputPower() <= power) {
				power -= v.building.getInputPower();
				v.building.setHasPower(true);
			}
			else
				v.building.setHasPower(false);
			for (BuildingTree c : v.childs)
				q.add(c);
		}
	}

	/**
	 * Recursively computes the total power generated by all buildings.
	 */
	private int computeTotalPowerOutput() {
		int power = 0;
		if (building != null)
			power += building.getOutputPower();
		for (BuildingTree c : childs)
			power += c.computeTotalPowerOutput();
		return power;		
	}
	
	/**
	 * Interface function for checkrequiredBuildings(boolean)
	 */
	public void checkRequiredBuildings() {
		// Moon Base has no required buildings.
		checkRequiredBuildings(false);
	}
	
	/**
	 * Checks if each building has its required buildings. This is true if 
	 * no higher node in the tree is empty.
	 * 
	 * @param isParentEmpty True if the parent node is empty. Means required 
	 * 						buildings are not available.
	 */
	private void checkRequiredBuildings(boolean isParentEmpty) {
		if (!isParentEmpty) {
			if (building != null)
				building.setHasRequiredBuildings(true);
			for (BuildingTree c : childs)
				c.checkRequiredBuildings(false);
		}
		else {
			if (building != null)
				building.setHasRequiredBuildings(false);
			for (BuildingTree c : childs)
				c.checkRequiredBuildings(true);
		}
	}
	
	/**
	 * Recursively checks how much resources are available in total, 
	 * considering resources used by buildings and non-working buildings.
	 * 
	 * @param resourceAvailable Previous amount of resources.
	 * @return List of resources that are available from buildings.
	 */
	public List<Resource> checkResources(List<Resource> resourceAvailable) {
		if (building != null && building.getHasPower() && 
				building.getHasRequiredResources()) {
			// Save values in case we need to reset available resources (if a 
			// building has some but not all of its resources available).
			List<Resource> oldAmount = new ArrayList<Resource>();
			for (Resource r : resourceAvailable)
				oldAmount.add(new Resource(r));
			
			for (Resource resourceNeed : building.getRequiredResources()) {
				if (subtractBuildingResources(resourceAvailable, resourceNeed)) {
					building.setHasRequiredResources(true);
					resourceAvailable = Resource.merge(resourceAvailable, 
							building.getOutputResources());				
				}
				else {
					// Reset resources so we don't remove part of the resources 
					// for a building that can't work.
					resourceAvailable = oldAmount;
					building.setHasRequiredResources(false);
				}
			}
		}
		for (BuildingTree c : childs) 
			Resource.merge(resourceAvailable, c.checkResources(resourceAvailable));
		return resourceAvailable;
	}

	/**
	 * If enough resources are available, those are removed from resource pool.
	 * 
	 * @return True if enough resources are available of each type.
	 */
	private boolean subtractBuildingResources(List<Resource> resourceAvailable,
			Resource resourceNeed) {
		for (Resource resourceHave : resourceAvailable) {
			if (resourceNeed.getName().equals(resourceHave.getName())) {
				if (resourceHave.getAmount() >= resourceNeed.getAmount())
					resourceHave.setAmount(resourceHave.getAmount() - 
							resourceNeed.getAmount());
				else
					return false;
			}
		}
		return true;
	}
}
